version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    parameters:
      img:
        type: string
    resource_class: "windows.medium"
    machine:
      image: << parameters.img >>

    steps:
      - checkout
      - run:
          name: check NVM
          shell: bash.exe
          command: |
            nvm -v

workflows:
  nvm:
    jobs:
      - build:
          matrix:
            parameters:
              img:
                - "windows-server-2019-vs2019:current"
                - "windows-server-2022-gui:current"
