version: 2.1 # Use version 2.1 to enable orb usage.

executors:
  win-gui-2023-04:
    machine:
      image: 'windows-server-2022-gui:2023.04.1'
    resource_class: 'windows.medium'
  win-gui-2023-06:
    machine:
      image: 'windows-server-2022-gui:2023.06.1'
    resource_class: 'windows.medium'
  win-gui-2023-07:
    machine:
      image: 'windows-server-2022-gui:2023.07.1'
    resource_class: 'windows.medium'

jobs:
  build: # name of your job
    executor: win-gui-2023-07
    steps:
      # approx: 450MB
      - run: |
          fsutil file createnew test50_0.txt 52428800
          fsutil file createnew test50_1.txt 52428800
          fsutil file createnew test50_2.txt 52428800
          fsutil file createnew test50_3.txt 52428800
          fsutil file createnew test50_4.txt 52428800
          fsutil file createnew test50_5.txt 52428800
          fsutil file createnew test50_6.txt 52428800
          fsutil file createnew test50_7.txt 52428800
          fsutil file createnew test50_8.txt 52428800
      - persist_to_workspace:
          root: .
          paths:
            - .
  attach:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      - attach_workspace:
          at: .

workflows:
  work-this-space:
    jobs:
      - build
      - attach:
          requires:
            - build
          matrix:
            parameters:
              exec:
                - win-gui-2023-04
                - win-gui-2023-06
                - win-gui-2023-07
