version: 2.1 # Use version 2.1 to enable orb usage.

executors:
  win-gui-2023-04:
    machine:
      image: 'windows-server-2022-gui:2023.04.1'
    resource_class: 'windows.medium'
  win-gui-2023-06:
    machine:
      image: 'windows-server-2022-gui:2023.06.1'
    resource_class: 'windows.medium'
  win-gui-2023-07:
    machine:
      image: 'windows-server-2022-gui:2023.07.1'
    resource_class: 'windows.medium'

jobs:
  build: # name of your job
    executor: win-gui-2023-07
    steps:
      # approx: 128 MB x 4 = 512 MB
      - run:
          name: generate files
          shell: bash.exe
          command: |
            echo "This is just a sample line appended  to create a big file. " > dummy0.txt
            for /L %i in (1,1,21) do type dummy0.txt >> dummy0.txt

            echo "This is just a sample line appended  to create a big file. " > dummy1.txt
            for /L %i in (1,1,21) do type dummy1.txt >> dummy1.txt

            echo "This is just a sample line appended  to create a big file. " > dummy2.txt
            for /L %i in (1,1,21) do type dummy2.txt >> dummy2.txt

            echo "This is just a sample line appended  to create a big file. " > dummy3.txt
            for /L %i in (1,1,21) do type dummy3.txt >> dummy3.txt
      - persist_to_workspace:
          root: .
          paths:
            - .
  attach:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      - attach_workspace:
          at: .

workflows:
  work-this-space:
    jobs:
      - build
      - attach:
          requires:
            - build
          matrix:
            parameters:
              exec:
                - win-gui-2023-04
                - win-gui-2023-06
                - win-gui-2023-07
