version: 2.1

executors:
  win-gui-2023-04:
    machine:
      image: 'windows-server-2022-gui:2023.04.1'
    resource_class: 'windows.medium'
  win-gui-2023-05:
    machine:
      image: 'windows-server-2022-gui:2023.05.1'
    resource_class: 'windows.medium'
  win-gui-2023-06:
    machine:
      image: 'windows-server-2022-gui:2023.06.1'
    resource_class: 'windows.medium'
  win-gui-2023-07:
    machine:
      image: 'windows-server-2022-gui:2023.07.1'
    resource_class: 'windows.medium'
  win-gui-2023-08:
    machine:
      image: 'windows-server-2022-gui:edge'
    resource_class: 'windows.medium'

jobs:
  build: # name of your job
    executor: win-gui-2023-07
    steps:
      - run:
          name: generate files
          command: |
            docker pull mcr.microsoft.com/windows/nanoserver:ltsc2019
            docker image save mcr.microsoft.com/windows/nanoserver:ltsc2019 -o nanoserver.tar
      - persist_to_workspace:
          root: .
          paths:
            # image is approx 250 MB
            # tar file is approx 90 MB
            - nanoserver.tar
  gitclone:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      # Start recording
      # - win-perf-diag/start-perflog
      # - win-perf-diag/record-wpr-in-background:
      #     for-sec: 100
      #     split-by-sec: 60
      - run:
          command: |
            git init
            git remote add origin https://github.com/arangodb/arangodb.git
            echo "Fetching stuff"
            git fetch --depth 1 origin 4192013cb700a80cc14d5f0a629b391209b07677
            git checkout 4192013cb700a80cc14d5f0a629b391209b07677
          name: Checkout ArangoDB
      # Stop recording and save records
      # - win-perf-diag/ensure-and-save-wpr
      # - win-perf-diag/stop-and-save-perflog

workflows:
  check-this-out:
    jobs:
      - gitclone:
          matrix:
            parameters:
              exec:
                - win-gui-2023-04
                - win-gui-2023-05
                - win-gui-2023-06
                - win-gui-2023-07
